# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mysql
  tag: 5.7.23
  pullPolicy: IfNotPresent
  
env:
  # must
  MYSQL_ROOT_PASSWORD: root
  TZ: "Asia/Shanghai"
  # optional
  MYSQL_DATABASE:
  MYSQL_USER:
  MYSQL_PASSWORD:

args: {}

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

service:
  enabled: false
  type: ClusterIP
  port: 3306
  # externalIPs:
  # - 192.168.1.1

config: 
  # lower_case_table_names: 1
  # character_set_server: utf8
  # max_connections: 500
  # max_connect_errors: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim: 
  # subPath: 

logs:
  parser: mysql

metrics:
  image: prom/mysqld-exporter:latest
  enabled: false
  group: mysql
  path: /metrics