apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
{{ include "service.labels.standard" . | indent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: "{{ .Values.name | default .Release.Name }}"
spec:
  accessModes:
{{ .Values.accessModes | toYaml | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.requests.storage | default "1Gi"}}
  {{- if .Values.storageClassName }}
  {{- if (eq "-" .Values.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.storageClassName }}"
  {{- end }}
  {{- else }}
{{- if .Values.volumeName }}
  volumeName: {{ .Values.volumeName }}
{{- end }}
  {{- end }}