kind: Pod
apiVersion: v1
metadata:
  name: write-pod
spec:
  containers:
    - name: write-pod
      image: busybox
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "touch /mnt/SUCCESS && exit 0 || exit 1"
      volumeMounts:
        - name: nfs-volume
          mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    pv: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    path: /opt/u01/prod
    server: 192.168.100.111

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: nfs-pv
