apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsmixcloud-provider-smcp-upms
  labels:
    app: smsmixcloud-provider-smcp-upms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smsmixcloud-provider-smcp-upms
    spec:
      containers:
      - name: smsmixcloud-provider-smcp-upms
        image: harbor.zthysms.com/ztinfo/smsmixcloud-gateway:v1
        ports:
         - containerPort: 4000
        imagePullPolicy: IfNotPresent
  selector:
    matchLabels:
      app: smsmixcloud-provider-smcp-upms
---
apiVersion: v1
kind: Service
metadata:
  name: smsmixcloud-provider-smcp-upms
  labels:
    app: smsmixcloud-provider-smcp-upms
spec:
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: smsmixcloud-provider-smcp-upms
